apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "app.fullname" . }}-allow-from-f5-ingress
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
  policyTypes:
    - Ingress