apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}
  ports:
  - name: oauth-proxy
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001
